# Generated by Django 3.0.5 on 2021-12-06 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_topping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topping',
            options={'verbose_name_plural': 'Toppings'},
        ),
        migrations.AlterField(
            model_name='topping',
            name='name',
            field=models.TextField(),
        ),
    ]
