# Generated by Django 3.0.5 on 2021-12-06 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0003_auto_20211205_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='data_added',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='topping',
            old_name='data_added',
            new_name='date_added',
        ),
    ]
