# Generated by Django 3.0.5 on 2021-12-06 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0004_auto_20211205_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topping',
            old_name='pizza',
            new_name='piz',
        ),
    ]
