# Generated by Django 3.0.5 on 2021-12-12 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0007_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='piz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pizzas.Pizza'),
            preserve_default=False,
        ),
    ]
